### ISSUE TITLE
[Calendar] Локализованные дни недели

### ISSUE THREAD

**Issue by pavel-b-novikov** [ksilobait/nsudotnet#1]
```csharp
mondayToSunday.DayOfWeek.ToString().Substring(0, 2)
```

Никуда не годится. Выводите дни недели локализовано, на языке системы, в которой запускается программа. И не хардкодьте.

**Comment by ksilobait** [comment]
сменил на использование DateTimeFormatInfo
про "не хардкодьте" не понял, стоит вынести "2" наружу как длину отображаемой части дня? но она неявно задана в некоторых Console.Write через отступы

**Comment by pavel-b-novikov** [comment]
Не-а. Там есть вполне себе человеческие сокращенные имена дней недели. Ищите, направление поиска правильное.

**Comment by ksilobait** [comment]
исправил на GetShortestDayName
