### ISSUE TITLE
[NumberGuesser] Минуты

### ISSUE THREAD

**Issue by pavel-b-novikov** [ksilobait/nsudotnet#3]
А если я планирую играть больше часа?

**Comment by ksilobait** [comment]
мне кажется, или это не самая интересная игра, чтобы в неё играть больше часа?
исправил .Minutes на .ToString

**Comment by pavel-b-novikov** [comment]
Нет, я хочу количество минут. И я хочу играть больше часа

**Comment by ksilobait** [comment]
исправил
